### ISSUE TITLE
Can't change icon of Webconsole Sample

### ISSUE THREAD

**Issue by vanlooverenkoen** [vletroye/Mods#10]
The package is still using the default image as icon in the Main Menu. But in the Package Manager the icon is correct as shown in the image below. (I also have added the privileges to this package)

![image](https://user-images.githubusercontent.com/21172855/33854282-6f81e716-dec1-11e7-8995-72299b9c4221.png)

**Comment by vletroye** [comment]
This is a known issue. DSM is not always refreshing "correctly" the icons. First, be sure that the Version is updated when you regenerate the package. Next, use CTRL-F5 to reload the DSM in your browser (possibly close/reopen the browser). Finally, if the old icon is really still used, change your "Package Name".

**Comment by vanlooverenkoen** [comment]
It has something to do with image-caching on DSM. If opend in another browser there is no problem :) ok thanks.

**Comment by vanlooverenkoen** [comment]
The image is updated after 7 days :) this is just caching on the Synoogy itself i guess.
