### ISSUE TITLE
Digital Signatures

### ISSUE THREAD

**Issue by craig1971** [vletroye/Mods#14]
This is a great tool.  I have created several example applications with it today.
on every install i get the warning that my package does not have a digital signature
Can MODS do this?  
If not how do I create/add a signature to my package?

**Comment by vletroye** [comment]
MODS can't do it. But it's doable with my own version of SSPKS. 
During installation of my SSPKS package, it should create public and private keys. 
Next, each spk files copied into the deployment folder of SSPKS can be signed via its web interface.

Here is the code: https://github.com/vletroye/sspks
Here are the sources for the package: https://github.com/vletroye/SynoPackages/tree/master/MODS%20Simple%20SPK%20Server
And here is my server where you can find the package: http://olympe.letroye.be/sspks/?arch=all

I have not written any doc yet... Hope you can find your path ;)
