### ISSUE TITLE
Script modules

### ISSUE THREAD

**Issue by Rasscal** [vletroye/Mods#15]
when adding a script to run there is no option to add a folder & supporting script/module for the executing script. 

"import appinfo
ImportError: No module named appinfo"

**Comment by vletroye** [comment]
I will plan to add support for that. 

In the meantime, you can simply drop your supporting script & module next to the script mods.sh created in the subfolder package/ui/<script>/

Press CTRL-E in MODS to open the folder containing your package.

**Comment by Rasscal** [comment]
Hi thanks for the quick reply,

Im trying the work around as suggested within a windows VM inside my NAS & when i click publish the mods.spk file disappears & throws out an error. This works fine on my normal desktop but i get the same results with three different windows versions within VM.

[error log.txt](https://github.com/vletroye/Mods/files/2556770/error.log.txt)

**Comment by vletroye** [comment]
The most common reason why the SPK can disappear is the antivirus. But usually, it's not deleted silently...

I have read the call stack of your error and only see one reason why it could have this error: if the spk is not correctly created. Could you open the folder "C:\Users\Administrator\Desktop\SynoPackages-master\MODS Various Samples\" and confirm that mods.spk exist after clicking on the menu "Package > Build" (CTRL-B)? Check also that this mods.spk file is not read-only.

When doing a CTRL-B: do you get an error message like "Creation of the package has failed." ?

And finally, did you open the folder C:\Users\Administrator\Desktop\SynoPackages-master\MODS Various Samples\ with mods.exe or did you open the spk file found inside ?

V.

**Comment by vletroye** [comment]
I have implemented a feature now for the scripts. You can drag & drop files or a folder onto a specific area. They will be copied next to your script

![image](https://user-images.githubusercontent.com/9768028/48318811-f7b72500-e605-11e8-9b08-3e72a3eb6091.png)

Also, now, pressing CTRL-E will open the folder containing the script while editing an existing script (instead of opening the root folder of the package)
