### ISSUE TITLE
Remotely opening a website on the same LAN as my NAS

### ISSUE THREAD

**Issue by acseven** [vletroye/Mods#16]
Hi,
I'm trying to use this to embed a UI for a device that is on the same local network as my Synology, in such a way that I can use DSM to open it using a direct remote connection to DSM. 
If I have a VPN connection open it will work (because remote addresses are reachable) but that beats the intended purpose. To make things worse the UI is essentially a Flash SWF file, making it even weirder to run (although it does open, eventually). 
Is this possible in any way?

**Comment by vletroye** [comment]
Unfortunately, it won't work as you expect. The embedding is just using an iFrame. It means that the browser displaying the DSM is calling directly the URL of the application to be embedded. 

You have indeed to use a VPN or open the required port to be able to access it remotely.
