### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by vanlooverenkoen** [vletroye/Mods#2]
Can you please make a guide on how to install your package from stratch? I have no idea where to start.

**Comment by vanlooverenkoen** [comment]
This helped me a lot:
https://github.com/vletroye/Mods/wiki/Illustration-Videos

The actual instalation is:
Adding **https://www.cphub.net to** download **Init 3rdparty**
![image](https://user-images.githubusercontent.com/21172855/33795141-65b07abe-dcdb-11e7-8b71-01c37870ffce.png)

Then follow this video to start your own package and install it on your DSM.
https://www.youtube.com/watch?v=nOaf_t26C6c&list=PLkgt4HbjgHDknDaQ-ZRPlEVp0nCF-nTBg&index=4

**Comment by vletroye** [comment]
Hello.

I indeed only mentioned the need to have this 3rd Party in the ReadMe: https://github.com/vletroye/Mods/blob/master/README.md

Adding the screenshot would make it more clear. I will anyway have to rewrite the doc, as I did add many features in the most recent sources... 

Kind regards,

 

                V.
