### ISSUE TITLE
Multiple User support

### ISSUE THREAD

**Issue by vanlooverenkoen** [vletroye/Mods#3]
You currently support Multiple Users. But what I am looking for is the possibility to only give permission to the package to 3 users. Is it possible to add your package to the Applications Privileges tab?
![image](https://user-images.githubusercontent.com/21172855/33795152-d6d22990-dcdb-11e7-8aed-cd4d29b348af.png)

**Comment by vletroye** [comment]
This was an interesting challenge…

I found a third party package with such a feature (IPKGui) and, looking at its config, was able to reproduce it in “Mods Packager”. I found details in http://www.synology-wiki.de/index.php/Aufbau_der_Datei_%27config%27

To use the privilege in your own pages, read this interesting article: http://www.synology-forum.de/showthread.html?33516-HowTo-3rdparty-Apps-Anwendungsberechtigung-und-SynoToken

If you only want to grant access to your URL's/Script of WebApp, it will work out of the box ;)

                V.

**Comment by vanlooverenkoen** [comment]
Can't get the acces to work. This is my setup?

![image](https://user-images.githubusercontent.com/21172855/33806238-7ac19fc4-ddc5-11e7-822e-ac31e0c1d1a5.png)

**Comment by vletroye** [comment]
That's really weird ?! I can't see any reason why the Grant Privilege combo is not there. Can you share with me your SPK file ?

![image](https://user-images.githubusercontent.com/9768028/33807949-c0a4b788-ddde-11e7-9f36-5773a002e040.png)

NB.: your url is incorrect... You are missing a / behind http:

**Comment by vanlooverenkoen** [comment]
If my window is maximized I couldn't see the "Grant Privilege". If the window is not maximized I can see the option. This is my current configuration. But my app is never shown in the Main Menu. In the package manager I can see that my package is running but it is not available in the Main Menu. all privileges are set to ALLOW. What am I doing wrong?

![image](https://user-images.githubusercontent.com/21172855/33851652-ea192e1c-deb7-11e7-95f7-5744ad1af259.png)

**Comment by vletroye** [comment]
Thx for the tip: I did fix the issue with the location of 'Grant Privilege' when resizing the window and will publish a new release asap.

In order to see the shortcut onto your url in the main menu, you need to select explicitly the option "Allow" in Control Panel > Privileges., for the required user (here under: for vletroye). If this user is already logged in, he has to log out and re-log in...

![image](https://user-images.githubusercontent.com/9768028/33852202-e59e4654-deb9-11e7-925e-2c5c904e553d.png)

**Comment by vanlooverenkoen** [comment]
AAH :) relogin maybe add this to your WIKI  aswell

**Comment by vletroye** [comment]
Wiki is sloooooowly under construction ;)

**Comment by vanlooverenkoen** [comment]
No problem :) thanks for the quick response
